# Generated by Django 4.0.2 on 2022-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_location_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_slug',
            field=models.SlugField(),
        ),
    ]
