# Generated by Django 4.0.2 on 2022-02-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_location_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='slug',
            new_name='location_slug',
        ),
    ]
