# Generated by Django 4.0.2 on 2022-02-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_location_location_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_slug',
        ),
    ]
